### ISSUE TITLE
wildcard input for CLI

### ISSUE THREAD

**Issue by jsen-** [Rich-Harris/sorcery#13]
It would be great if Sorcery supported recursive walk of directories, processing all *.js* files it finds along the way.
The output directory could be specified, effectively mimicking the directory structure of input dir inside the output dir.

Something like
```sh
sorcery --source-dir src --out-dir dist
```

**Comment by Rich-Harris** [comment]
Agree. I don't have time to work on this right now but would gladly accept a PR :-)

**Comment by jsen-** [comment]
I kinda expected an answer like this as I'm in a similar situation right now :)
I'll try to find some time in, let's say, near future ...
I'll leave a comment here before I begin.

**Comment by Seikho** [comment]
@Rich-Harris, are you still open to accepting a PR on this?

**Comment by Rich-Harris** [comment]
This is now implemented, in 0.10
