### ISSUE TITLE
Switch to @jridgewell/sourcemap-codec to avoid deprecation warnings in libraries that depend on sorcery

### ISSUE THREAD

**Issue by falynx** [Rich-Harris/sorcery#178]
Hi Rich, you deprecated [sourcemap-codec](https://github.com/Rich-Harris/sourcemap-codec) in favor of [@jridgewell/sourcemap-codec](https://github.com/jridgewell/sourcemap-codec). [svelte-preprocess](https://github.com/sveltejs/svelte-preprocess) currently depends on this sorcery library, which results in a deprecation warning.

```bash
$ pnpm up --latest
 WARN  deprecated sourcemap-codec@1.4.8: Please use @jridgewell/sourcemap-codec instead
Already up to date
Progress: resolved 456, reused 434, downloaded 0, added 0, done
Done in 5.2s
```

**Comment by Rich-Harris** [comment]
This was fixed in 15e2b236693f109032f9a8a90b69003fdbada62f
