### ISSUE TITLE
sourceMappingURL can contain whitespace characters

### ISSUE THREAD

**Issue by MartinKolarik** [Rich-Harris/sorcery#6]
I've just got a weird ENOENT error while trying to build Ractive, and after a while I was able to track it down to [this line](https://github.com/Rich-Harris/sorcery/blob/f3cce71832d737e56743330326b6890844deb100/src/utils/getSourceMappingUrl.js#L12).

**Comment by Rich-Harris** [comment]
Ah, whoops. Thanks for tracking it down. I suspect whitespace characters are supposed to be %-encoded by the time they're used as a `sourceMappingURL`, probably something else I need to fix. In the meantime though, changing it to `match = /^[^\n]+/.exec( substring )` ought to do the trick - does that sound about right?

**Comment by MartinKolarik** [comment]
>I suspect whitespace characters are supposed to be %-encoded by the time they're used as a sourceMappingURL

Ah, yes, they actually are. In that case it's probably esperanto that needs fixing.

>In the meantime though, changing it to match = /^[^\n]+/.exec( substring ) ought to do the trick - does that sound about right?

I think that would fail with CRLF endings. Probably an edge case, but changing it to `/^[^\r\n]+/` is easy enough.

**Comment by Rich-Harris** [comment]
> I think that would fail with CRLF endings

Good catch. Have released this as 0.4.0, and opened a corresponding issue on esperanto

**Comment by MartinKolarik** [comment]
:+1:
