### ISSUE TITLE
Collision in sourcemap cache with crc32

### ISSUE THREAD

**Issue by meirgottlieb** [Rich-Harris/sorcery#73]
Hello, I'm getting collisions in the cache that uses the crc32 in this file https://github.com/Rich-Harris/sorcery/blob/master/src/utils/decodeMappings.js. I removed the caching mechanism and everything works fine. It doesn't really add much to the execution time removing the cache.

**Comment by Rich-Harris** [comment]
Released 0.9.4 with the fix – thanks

**Comment by meirgottlieb** [comment]
Thank you for the quick turnaround.
